### ISSUE TITLE
Invalid license

### ISSUE THREAD

**Issue by gdude2002** [ByMartrixx/yarn-cli#1]
Hello! I'm the person that wrote the majority of the code in Fabric Bot. I just wanted to let you know that you appear to be *barely* breaking the terms of [the license](https://github.com/FabricMC/fabric-discord-bot/blob/rewrite/LICENSE).

The MIT is fairly loose in restrictions, but I believe you need to include it with any copies of the project or code therein. This project has no license - that means it's actually All Rights Reserved, which I doubt is what you were going for anyway.

Additionally, there were many issues with the approach we took with Fabric Bot. I ended up writing a brand new extension that made use of linkie-core, and generally works far better (and isn't limited to yarn). You can find it here, if you feel like improving your project the same way: https://github.com/Kord-Extensions/ext-mappings

**Comment by YTG1234** [comment]
> but I believe you need to include it with any copies of the project or code therein.

I believe so too. The MIT license is a short one, and it's not very difficult to see the single condition:

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

**Comment by gdude2002** [comment]
Yep. Note that this does **NOT** mean that this project must also be licensed under the MIT - just that it must be pointed at.

**Comment by ByMartrixx** [comment]
Thanks for letting me know! I usually use the MIT license, so I'm aware of the conditions of it - looks like I forgot to add both the Fabric Bot code license and the repo license.
Would adding a header with the license be enough? Or should I do it in another way?

**Comment by gdude2002** [comment]
I'm sure that's fine, although I usually include a second license file (eg
`LICENSE-MIT` or `LICENSE-FABRIC-BOT`) in the repo and reference it in the
README

**Comment by ByMartrixx** [comment]
Fixed it!
