### ISSUE TITLE
What for?

### ISSUE THREAD

**Issue by liach** [ByMartrixx/yarn-cli#2]
Is this just a command line tool so you can look up yarn mappings? How is this significantly better than using like grep to find strings?

**Comment by ByMartrixx** [comment]
Yes, it is. With it you don't have the need to manually download the mappings you need, it does that for you, and can give you some useful information like Access wideners or descrpitors so you don't have to write them manually

**Comment by liach** [comment]
Cool thanks. Though if I make one I'd make a javafx application
